ports :
  gin : "1200"
database :
  pgdb :
    db_url:  "%s://%s:%s@%s:%s/%s?sslmode=%s"
    db_type: "postgres"
    db_user: "postgres"
    db_pass: "postgress"
    db_host: "127.0.0.1"
    db_port: "5432"
    db_name: "movies"
    db_additional:
      postgres_ssl_mode: "disable"
